#!/bin/sh

# PROVIDE: zabbix_agentd
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to
# enable zabbix_agentd:
#
# zabbix_agentd_enable (bool): Set to NO by default.  Set it to YES to
#         enable zabbix_agentd.
#

. /etc/rc.subr

name="zabbix_agentd"
rcvar=zabbix_agentd_enable

command="/usr/local/sbin/${name}"
required_files="/usr/local/etc/zabbix2/${name}.conf"

load_rc_config $name

: ${zabbix_agentd_enable="NO"}

run_rc_command "$1"
